### ISSUE TITLE
Reorganize Project Files

### ISSUE THREAD

**Issue by Wafflemon** [janusvr/janus#1]
Eww gross. There's no documentation or directory structure for your source files. Furthermore, your build files are intermixed with your source files -- that's just plain madness. Isn't JanusVR a real company that has existed for 4 years? At first glance, it kind of looks JanusVR was originally a startup with inexperienced developers (in a real production environment anyway) and now has a lot of technical debt. I personally wouldn't write anything significant against an open sourced platform that lacks organization and documentation.

**Comment by jbaicoianu** [comment]
Do you have any recommendations for how you'd like to see it done?  As an open source project, we would like to take constructive feedback into account - however, as submitted, this is not particularly constructive.

Please refer to CONTRIBUTING.md for guidelines about how to file Github issues which provide specific, actionable feedback about bugs or enhancements you'd like made. If you just want to vent, feel free to join our Discord or IRC channels, but this is not the place for that.

**Comment by jbaicoianu** [comment]
Sorry, didn't mean to close the issue - if you can provide specific feedback about how you think it should be structured, please feel free to leave them as comments.

**Comment by JamesMcCrae** [comment]
Cleanup step 1 13c0e1702b919a8bd3927d0c5562db0b2b06bc6c

**Comment by JamesMcCrae** [comment]
Cleanup step 2 c8104b31618e1644755728ce62a6ce4363fc3a26

**Comment by JamesMcCrae** [comment]
Cleanup step 3 e2332b34fec009b36a28761a19809a3a8c545fda

**Comment by JamesMcCrae** [comment]
Cleanup step 4 1ad78b27f14b75a74898b166f50d3652ab648a39

**Comment by JamesMcCrae** [comment]
Cleanup step 5 650951395e930f60420f62ce507ab666cbd08c6a

**Comment by JamesMcCrae** [comment]
Cleanup step 7 709de9c8f25842f05f7540358f511be65030798a

**Comment by JamesMcCrae** [comment]
Cleanup step 8 0d95ccede7aba00d78647113129ba9d9d7c921b9

**Comment by JamesMcCrae** [comment]
Cleanup step 9 723670372c0ce2200752173ff7fbeb3b27979885

**Comment by JamesMcCrae** [comment]
Cleanup step 10 9966922df8e980a37ab9a4652d97a3a61ce9b4e1

**Comment by JamesMcCrae** [comment]
Cleanup step 11 eae70a7b531b08088d5027450681a2244a0ca66f

**Comment by JamesMcCrae** [comment]
Cleanup step 12 2e8fc15e6f8861632772b7836d75b85df1d473cf

**Comment by JamesMcCrae** [comment]
Cleanup step 13 8623187689e2f9912ec6123deddff309254e8e38

**Comment by JamesMcCrae** [comment]
Cleanup step 14 7e8a1e6f9dd31b7eae1e55618b683ae84564bf5f

**Comment by JamesMcCrae** [comment]
Cleanup step 15 b406f74a94962623f6361fd03b31880176cc902f

**Comment by JamesMcCrae** [comment]
Cleanup step 16 81eb3c54c5814d928ded38318e09aacb4a92b0b9

**Comment by JamesMcCrae** [comment]
Cleanup step 17 77f51ffe1b875b6cb189ea8eeb978a0ebde20519

**Comment by JamesMcCrae** [comment]
Cleanup step 18 3beb49badf7e447d01d46dbbc9306081c5876f05

**Comment by JamesMcCrae** [comment]
Cleanup step 19 3260a69e15f6130fddd25fa3263f35b18ae4d1c4

**Comment by JamesMcCrae** [comment]
Cleanup step 20 8b31c35612f62a33f597f1cc442fde1ed17768ea

**Comment by JamesMcCrae** [comment]
Cleanup step 21 57419683e81251391546013c9aaa29542477f02b

**Comment by shadoxx** [comment]
Looks like this issue has been addressed. Should we close it?

**Comment by jbaicoianu** [comment]
Yup, I think so. Any additional cleanup suggestions can be made by filing new issues.
