### ISSUE TITLE
[bug] Mirror surfaces cause loading of all other assets to halt

### ISSUE THREAD

**Issue by ghost** [janusvr/janus#1]
this happens both with and without the ```url="http://my.url.com"``` tag
test:
```xml
<Link js_id="mirsur" pos="0 1 0" scale="2.8 1.5 1" fwd="0 0 -1" auto_load="true" draw_text="false" draw_glow="true" mirror="true" active="false"></Link>
```

**Comment by JamesMcCrae** [comment]
![image](https://user-images.githubusercontent.com/1403837/63226968-43a78380-c1af-11e9-80a2-600addc95467.png)

Am able to reproduce this bug.  Will work on it now.

**Comment by JamesMcCrae** [comment]
![image](https://user-images.githubusercontent.com/1403837/63228587-1a90ee00-c1c3-11e9-8c09-c16101059e0c.png)

I have a fix.  Assets in the mirror room were not being updated, causing threads to be consumed and not released.  Will be fixed in next commit.

**Comment by JamesMcCrae** [comment]
https://github.com/janusvr/janus/commit/a557a720dc6d143c251e6236a64f20ee6803ec1b

Fixed in that commit.  Thanks for this one!  Good bug to fix.

**Comment by ghost** [comment]
Thanks, and good work :)
