### ISSUE TITLE
Drag and Drop from websurfaces not working

### ISSUE THREAD

**Issue by madjin** [janusvr/janus#12]
Used to be able to drag n' drop assets from a websurface into the room but this feature has been broken for awhile. Lets restore this [news-worthy](http://prostheticknowledge.tumblr.com/post/126543151131/janus-vr-drag-and-drop-latest-update-to-the-3d) feature back into the latest version.

**Comment by joseph-cruz** [comment]
Fixed as of bdf1c35.
