### ISSUE TITLE
Fullscreen mode does not hide auto-hide address bar

### ISSUE THREAD

**Issue by madjin** [janusvr/janus#13]
The address bar persists into fullscreen (F11) mode. It should work how you expect mainstream browsers such as chromium or firefox to work, hiding everything for full immersion until you move your mouse up there to activate it again.

**Comment by JamesMcCrae** [comment]
Fixed in commit https://github.com/janusvr/janus/commit/dbb139bea9571cdccbbdab8be96abc761e8b0b6c

Closing.
