### ISSUE TITLE
[bug] portal disappears and becomes unusable

### ISSUE THREAD

**Issue by ghost** [janusvr/janus#2]
Shown in this video
https://www.youtube.com/watch?v=Diq2_CKaJZI

**Comment by JamesMcCrae** [comment]
Did some refactoring to simplify portals and navigation.  This bug will be fixed in 66.3.  Thanks as always!

![image](https://user-images.githubusercontent.com/1403837/63316616-7354a980-c2dd-11e9-8ea5-11e0bfdd7a9f.png)

**Comment by JamesMcCrae** [comment]
Commit https://github.com/janusvr/janus/commit/bcc303c425c7946b66742f347a5db2d8d30b9e60

**Comment by ghost** [comment]
No, thank YOU :) as always :D
