### ISSUE TITLE
Can't delete spawned portals.

### ISSUE THREAD

**Issue by madjin** [janusvr/janus#22]
Spawn portal, can't delete.

**Comment by JamesMcCrae** [comment]
If you close the portal, then delete it should work.  But this can probably be considered a bug, as it should not be necessary to manually close the portal in order to delete it.

**Comment by JamesMcCrae** [comment]
Fixed in commit [master 95767d0b] release 61.0 bugfix allow deletion of open portals/Links
 1 file changed, 21 insertions(+), 20 deletions(-)
