### ISSUE TITLE
Fog is affecting the skybox

### ISSUE THREAD

**Issue by madjin** [janusvr/janus#24]
I noticed that in a room that has fog the skybox does not become visible. I can't understand why one might think this is a good idea in scenes. I've asked other creators and they prefer being able to still see the skybox when there is fog. I recommend fixing it for fog to look similar to how it looks in Janusweb as reference since it gives us the most options and flexibility.

Here's a test site: https://vesta.janusvr.com/bepis/tree-sway

**Comment by JamesMcCrae** [comment]
Fixed in commit [master be838b33] release 61.0 bugfix handle error when some skybox_ids are missing, bugfix do not have fog affect skybox, bugfix fix error texture
 5 files changed, 25 insertions(+), 14 deletions(-)
