### ISSUE TITLE
Some rooms crash with code editor open

### ISSUE THREAD

**Issue by madjin** [janusvr/janus#25]
Couple of us notice some sites immediately crash when the code editor is opened. In order to debug, might be helpful have the code editor open before clicking portals because the crash happens as soon as you walk through.

**Comment by JamesMcCrae** [comment]
This issue is no longer present since a couple weeks back.  Relevant commits for stability:

https://github.com/janusvr/janus/commit/4970f8a7aa0b415276ba094a1dadc3ecc128a8ab
https://github.com/janusvr/janus/commit/bee1262f64558cf10c4fb14da47532ebcab264cb
