### ISSUE TITLE
"Save-as" json export is broken

### ISSUE THREAD

**Issue by madjin** [janusvr/janus#26]
Currently when you save-as ".json" from the Janus client it will write the file in XML. This feature is important right now while researching ways we can take json saves from platforms like Anarchy Arcade and to be able to read/write it into a Janus friendly format.

**Comment by JamesMcCrae** [comment]
Fixed in commit [master 52b185b1] release 61.0 refactor add back the JSON export function, bugfix do not save out internal skybox_error_ids
 7 files changed, 644 insertions(+), 4 deletions(-)
