### ISSUE TITLE
error with alpha channel transparency in mtl file

### ISSUE THREAD

**Issue by madjin** [janusvr/janus#27]
Noticed that the palm trees aren't slightly transparent in native with this room example: https://vesta.janusvr.com/bepis/tree-sway/

It has to do with the alpha channel in the mtl file:

https://vesta.janusvr.com/files/bepis/garden/palm2/palm_tree2.mtl

This part defines the non-transparency of the material to be alpha.
d 0.500000

**Comment by JamesMcCrae** [comment]
Fixed in commit [master 51c09f66] release 61.0 bugfix material diffuse transparency parameter
 1 file changed, 2 insertions(+), 2 deletions(-)
