### ISSUE TITLE
feature request: cycle through primitives when editing collision_id

### ISSUE THREAD

**Issue by madjin** [janusvr/janus#32]
Sometimes cubes aren't the best default, we need to pick something that fits. Being able to cycle through the primitives cube, sphere, cone, capsule, cylinder when you are editing an objects collision_id is much faster than manual way of sifting through the code.

**Comment by JamesMcCrae** [comment]
Added in commit https://github.com/janusvr/janus/commit/38823667a6c3ae2a2bc5d07a99db75e00448a838
