### ISSUE TITLE
Missing Textures on FBX with included textures

### ISSUE THREAD

**Issue by source83** [janusvr/janus#39]
I don't know if this is an issue on windows/osx/android/ios?
This has been an issue on linux for a while now.

**Comment by JamesMcCrae** [comment]
Fixed in commit https://github.com/janusvr/janus/commit/e884bfa19e54b5757dc2ff34b79947fc04f4cba4 for the model I tested on that had this problem.

Let me know if you still see this bug (and link me to the file).  Closing for now.
