### ISSUE TITLE
bug: cylinder collision mesh (possibly others) are spanning lower that specified

### ISSUE THREAD

**Issue by source83** [janusvr/janus#40]
When setting a cylinder collision mesh on a object, the mesh is centered at the bottom of the object instead of the center, so the bottom half of the collision mesh spans below the object.
This is evident on cylinder collider mesh on a object where center is the object's lowest point.
Also, if collider is shifted up or down, no difference is detected.
Can provide video, pictures and/or demo room if needed.

**Comment by JamesMcCrae** [comment]
This commit adds back the collision_pos attribute, it may fix the issues you mention https://github.com/janusvr/janus/commit/e8ccc01913e318502768784cd05c1064f48f1373
