### ISSUE TITLE
Feature request: set object wheight and/or 'bouncyness'

### ISSUE THREAD

**Issue by source83** [janusvr/janus#41]
This would help prevent objects with small collision meshes in physics mode from bouncing like rubber balls when they are supposed to be metal (for example).

**Comment by JamesMcCrae** [comment]
Attributes added in commit https://github.com/janusvr/janus/commit/3ec314e7f301a70f4efb719732df4237fc380d6d

Brief documentation on new object attributes (see the bullet library documentation for additional info, see the restitution coefficient in particular for bounce):

collision_friction (float, default "0.5")
collision_rollingfriction (float, default "0.01")
collision_restitution (float, default "0.85")
collision_angulardamping (float, default "0.1")
collision_lineardamping (float, default "0.15")
