### ISSUE TITLE
Janus crashes when typing Text tags

### ISSUE THREAD

**Issue by madjin** [janusvr/janus#43]
In order to reproduce, go into a room with another person and make a Text object (Shift+Right click) then start typing and backspacing really quickly to delete it again.

http://janusvr.com/docs/build/roomtag/index.html#Text

**Comment by JamesMcCrae** [comment]
Hopefully fixed by commit https://github.com/janusvr/janus/commit/ebe39e9ac5275edc094b58f19c8504a42ffd79bd
