### ISSUE TITLE
Native client doesn't render some transparencies

### ISSUE THREAD

**Issue by cfravel** [janusvr/janus#44]
Working on the Decentraland pipeline, and working on transparency (foliage, and glass for windows)
Discovered two methods for making transparencies that work in all of the following contexts
- Blender (and export from 2.80 to gltf)
- BabylonJS Sandbox (using the gltf)
- Decentraland SDK (using the gltf)
- JanusWeb (Vesta) 
These two methods both involve using the new Principled BSDF and Transparency BSDF shaders in Blender 2.80, and exporting gltf.
One method uses a color texture png file with alpha, that controls the Mix Shader.
The other method uses the same shaders, but with alpha settings instead of using an alpha in image.
Full documentation as well as sample files here:
https://docs.google.com/document/d/1VWmlSanvvFZbtXD_pR4D1NE0kQ3MEwsCRkrXKwfVQGE/edit#

Here is a Vesta scene demonstrating these two methods of transparency, with different tints/transparency samples:
https://vesta.janusvr.com/carlfravel/decentraland-blender-transparency-demo

The transparency works in JanusWeb  (the 2nd and 6th object pairs are almost completely invisible)

In Native, only the objects whose alpha is controlled by an alpha channel in a .png image file are transparent.

**Comment by JamesMcCrae** [comment]
Checked the .gltf file contents to find the alpha component:

![image](https://user-images.githubusercontent.com/1403837/53706516-bfc42f80-3df8-11e9-823a-41987f918607.png)

Our conversion function QColor Geom::GetColourFromArray(float * c) was ignoring the final alpha component, making it always 1, so I did the fix:

![image](https://user-images.githubusercontent.com/1403837/53706523-c5ba1080-3df8-11e9-9d3a-20d026173911.png)

Commit is https://github.com/janusvr/janus/commit/8ed364d1f2620b68f39779f3fe43023e715cf356
