### ISSUE TITLE
gltf object with "ground plane" flickers unless set to about 0.05m up

### ISSUE THREAD

**Issue by cfravel** [janusvr/janus#46]
You can see that in a clone of the following demo scene
https://vesta.janusvr.com/carlfravel/blender-transparency-demo-for-decentraland

If i set the vertical location of this gltf to zero a few milimeters less, it flickers
if i set it to 0.1 it doesn't flicker until look down from quite a height.
`  <Object id="https://vesta.janusvr.com/files/CarlFravel/DecentralandBlenderTransparencyDemo/DecentralandBlenderTransparencyDemo.gltf" js_id="CarlFravel_7550-2-1551716462" pos="-8 0.05 15" xdir="-1 0 0" zdir="0 0 -1" collision_id="https://vesta.janusvr.com/files/CarlFravel/DecentralandBlenderTransparencyDemo/DecentralandBlenderTransparencyDemo.gltf" />
`

**Comment by cfravel** [comment]
nvm, my ground plane object was slightly below the ground
d'oh

**Comment by JamesMcCrae** [comment]
This sounds like classic z-fighting.  You might try playing with the near_dist and far_dist Room attributes, which affect the near and far plane rendering distances.  Tuning these for your Room can make things more fine-grained over the depth range you need it to work for, and avoid the z-fighting/flickering effect.

**Comment by JamesMcCrae** [comment]
Alternatively, you may not want to render the default ground plane itself.  You can remove it by removing the use_local_asset="plane" part in the Room tag.
