### ISSUE TITLE
JanusVR doesn't handle/ignore the version parameter added by dragging a replacement file from Inventory

### ISSUE THREAD

**Issue by cfravel** [janusvr/janus#47]
JanusVR doesn't handle the version parameter added by dragging a replacement file from Inventory

Steps to reproduce
1. Place a gltf unembedded file set into a directory in Vesta my_files inventory
2. Delete the contents of that directory
3. Put revised fileset (same filenames) into that inventory directory
4. Drag from that inventory into a JanusVR native scene
5. Note that the AssetObject tag's url has a version number on it now.
like this:
`<AssetObject id="https://vesta.janusvr.com/files/CarlFravel/DecentralandBlenderTransparencyDemo/DecentralandBlenderTransparencyDemo.gltf?v=1551718777" src="https://vesta.janusvr.com/files/CarlFravel/DecentralandBlenderTransparencyDemo/DecentralandBlenderTransparencyDemo.gltf?v=1551718777" />`
This causes the asset not to be loaded in JanusVR native, and if it is the only mesh object, then you also get this error in the native Log:

Geom::Load() Error: Validation failed: aiScene::mNumMeshes is 0. At least one mesh must be there Path: https://vesta.janusvr.com/files/CarlFravel/DecentralandBlenderTransparencyDemo/DecentralandBlenderTransparencyDemo.gltf?v=1551718777

**Comment by JamesMcCrae** [comment]
Fixed in commit https://github.com/janusvr/janus/commit/22950943389dd120438cfa942c1372ff1249b711

![image](https://user-images.githubusercontent.com/1403837/53762369-eedcae80-3e95-11e9-9112-b882e705e535.png)
