### ISSUE TITLE
JanusVR doesn't support glTF 2.0 (janusweb does)

### ISSUE THREAD

**Issue by cfravel** [janusvr/janus#5]
Steps to repo:
Get a model with textures into blender
Export it to gltf 2.0 with Khronus plugin
Put it into JanusVR
// expected see it
// actual it's in the markup but not visible

**Comment by JamesMcCrae** [comment]
We are using a recent version of assimp, which should support glTf 2.0 (at least, it should in theory anyway).  

There is a known (and possibly related issue) where it may not worth if the .bin files are embedded into the main file or not, see:

https://trello.com/c/x7PD6nRu/1073-gltf-20-support-bin-doesnt-load-because-of-an-extra-slash-in-the-path-works-if-the-bin-is-embedded-into-the-gltf

Do you have an option the blender exporter to toggle .bin embedding?  Also, if you can give us a link to the gltf file ourselves we can have a look and do independent testing.

**Comment by cfravel** [comment]
The Khronos exporter can create gltf or gltb (embedded) files, but the Decentraland SDK only supports the not-embedded format.

Here is a scene that bai made with gltfs that works in JanusWeb but not JanusVR...
https://vesta.janusvr.com/bai/gltf-test

**Comment by cfravel** [comment]
@JamesMcCrae 
So here's what i've learned...

1. JanusWeb accepts drag and drop of gltf without embedding, and shows it properly
2. JanusWeb does NOT show gltfs with embedding.
3. JanusVR accepts drag and drop of glTF with embedded mesh and images, but doesn't show the material/texture
4. JanusVR does not show glTFs that don't have embedding.
5. Decentraland SDK works with either embedded or non-embedded glTFs

Example Scene:
http://www.fravel.net/webvr/JanusGltfTest/

My component palette for building this scene:
http://www.fravel.net/webvr/AetheriaContentLibrary/

In my palette:
Lady is gltf with separate .bin and image files in same inventory/palette server folder as the gltf
Gate is gltf with all the content embedded.

BTW, in the Khronos gltf exporter, export gltf not glb, and then check the two embedding checkboxes (buffer, images), but NOT the strip delimiters one

So:
JanusVR needs to show the textures for the gltf-embedded format
JanusWeb needs to show the gltf-embedded format

**Comment by madjin** [comment]
Getting an error in the console log:

Geom::Load() Error: No suitable reader found for the file format of file "https://vesta.janusvr.com/files/shadoxx/club/scene.gltf". Path: https://vesta.janusvr.com/files/shadoxx/club/scene.gltf

Test site: https://vesta.janusvr.com/shadoxx/the-club

**Comment by JamesMcCrae** [comment]
Yeah, I get that error too.  Might try updating the version of assimp we are linking with as a first step toward fixing this.

**Comment by JamesMcCrae** [comment]
glTF 2.0 files are now working (both embedded and non-embedded) as well as GLB (though there may be some specific texture bugs to address next).  See commits:

https://github.com/janusvr/janus/commit/43a0962794b53edd253f8944cb4cb1e9ce91c154

https://github.com/janusvr/janus/commit/60acf9a9bffe3f1c1aa7ef053e8d29960ae1bcdb

https://github.com/janusvr/janus/commit/932099a0f2d1ea647716b96222194ec0a2a73f32
