### ISSUE TITLE
Feature Request: random "spawn point" from list of <room> positions

### ISSUE THREAD

**Issue by source83** [janusvr/janus#50]
I did a little coding on this idea myself, but the variables in qtc++ are a bit to confusing for me.

The idea is to have pos="x y z" and if apos(1-4)="x y z" is set in the room code,
the client will chose at random between pos and apos1-4 as the "spawn point"
when entering the room and possibly also when reloading the room.

Possible examples:
```<room pos="0 0 0" apos1="10 0 10" apos2="10 0 -10" apos3="-10 0 10" apos4="-10 0 -10"></room>```

```<room pos="0 0 0" apos="10 0 10, 10 0 -10, -10 0 10,-10 0 -10"></room>```

Possibly some for of dictionary or array might make it possible to have more than 4/5 positions.

**Comment by JamesMcCrae** [comment]
Why not just use a script to do this?  i.e. set the `player.pos` in `room.onLoad()` ?

**Comment by source83** [comment]
D'oh, didn't think that far.
You are fully correct in that :smile:

**Comment by JamesMcCrae** [comment]
`room.onLoad = function() { player.pos.x = Math.random() * 10.0}`
