### ISSUE TITLE
[bug] FBX model textures not loading

### ISSUE THREAD

**Issue by source83** [janusvr/janus#55]
error_log.txt says that janus is trying to load the textures from a completely wrong location even if the textures are external:
```https://jvr.junkonet.org/home/app/mixamo-mini/tmp/skins_beec3bd9-d801-4137-9243-32ea51f2f557.fbm/quiet__gear_d.jpg```
and
```https://jvr.junkonet.org/storage/Local/Google Drive/Assets/Textures/10x10 single color/black.png```
These paths are completely invalid and are references to old paths in part.

**Comment by JamesMcCrae** [comment]
Can you give me a link to the FBX file itself?

**Comment by source83** [comment]
http://jvr.junkonet.org/models/slenderman-models/slenderman/Slender.fbx.gz
and more.

**Comment by source83** [comment]
Sorry, that is wrong. for some reason the texture is loading for that slenderman model, but not for some others.
I have one specefic one that janus won't load the textures for, but it's nsfw so...

**Comment by source83** [comment]
https://jvr.junkonet.org/?roomid=36
or the model only:
https://jvr.junkonet.org/models/gizmo.fbx

**Comment by JamesMcCrae** [comment]
Tested link, and both models appear to work on Windows for 63.0.

![image](https://user-images.githubusercontent.com/1403837/60448689-1f3e1a80-9bf4-11e9-8ddc-5c03fd57e11b.png)

**Comment by JamesMcCrae** [comment]
It appears this bug affects the Linux build of 63.0 only.

![image](https://user-images.githubusercontent.com/1403837/60449106-f0747400-9bf4-11e9-83fb-2ef93e8c4bf9.png)

**Comment by JamesMcCrae** [comment]
Fixed in 63.1.  Commit: https://github.com/janusvr/janus/commit/ede08ad3c522405c8c328abb165087f5f7acc797

![image](https://user-images.githubusercontent.com/1403837/60450476-f0c23e80-9bf7-11e9-8eb5-a42e3be8992c.png)
