### ISSUE TITLE
Compiling bug that happened after 65.6

### ISSUE THREAD

**Issue by source83** [janusvr/janus#58]
Version 65.6 commit 75b05b9abcb589ebe75589594a865ad9f1e375e2 is the last commit that compiles.
Version 65.7 commit 24786140d89a7d159a7a002ac72e00ae9998a027 and above do not compile anymore.

Also, `make clean` doesn't remove the janusvr binary in the root directory so even if you do a `make clean` on the later versions, you still get the same old binary with no changes since 65.6

**Comment by JamesMcCrae** [comment]
What is this error you get?

Do you have the Qt WebEngine module installed?

QtWebEngine module started to get linked in for commit https://github.com/janusvr/janus/commit/24786140d89a7d159a7a002ac72e00ae9998a027 and beyond.

**Comment by source83** [comment]
I am sorry, it looks like that was exactly what was causing my problems.
I should have done more investigating before posting an issue.
Thank you for the help!
