### ISSUE TITLE
Cannot rotate 90 degrees in edit mode

### ISSUE THREAD

**Issue by madjin** [janusvr/janus#6]
Went to test this in a new page, spawned a primitive, and then rotated by 15 degrees - works.. but then if I try to rotate 90 degrees it rotates once then nothing happens after. Using version 60.0.6360a0d windows 10.

**Comment by JamesMcCrae** [comment]
There was a bug with interpolation and the basis vectors losing their new assignment.  This has been fixed, see:

https://github.com/janusvr/janus/commit/0667aad8dda2603ca8d9cd4c5cc4d05f1b67d2e3
