### ISSUE TITLE
WebSurfaces don't support localStorage

### ISSUE THREAD

**Issue by Ronsor** [janusvr/janus#7]
You will always receive an error of "QUOTA_EXCEEDED."

This is easy to reproduce by going to "http://windows93.net" in a websurface. You will receive a popup with the QUOTA_EXCEEDED error.

**Comment by joseph-cruz** [comment]
Fixed in commit 8d33ad8 in the Android branch. Should be available once it's merged into master.

**Comment by JamesMcCrae** [comment]
Merged android branch.
